Henry's information added
qiyunlab/qiyunlab.github.io pull request #10
Opened 2021-03-09 09:30 UTC by HSecaira

Dear Dr. Zhu, 

I added my cv, photo, and information to the people.md file. 

Let me know if I must change something. Thanks!

2021-03-09 15:54 UTC, qiyunzhu commented
@HSecaira Very good! Welcome on board! Just a trivial note: Your picture is in portrait direction with black edges on top and bottom, which may stretch the layout in the "People" page. Would you mind trimming the edges?

2021-03-09 21:22 UTC, HSecaira commented
@qiyunzhu  I have cropped my photo. Let me know if it works. Thanks!

2021-03-10 08:31 UTC, qiyunzhu requested changes

2021-03-10 08:31 UTC, qiyunzhu commented on people.md
> +    image_path: assets/images/people/HenryPhoto.jpeg
@HSecaira Don't forget to modify the image file name too since your cropped image has a different name.

2021-03-10 09:16 UTC, HSecaira commented
@qiyunzhu sorry about that. The image file name has been modified. Let me know if there is something else I should change. Thanks!

2021-03-10 16:10 UTC, merged